image:
  file: .gitpod.Dockerfile

tasks:
  - init: npm install
    command: npm start
  - init: |
      cd backend
      npm install
      npm run dev
    command: |
      cd backend
      npm start
  - init: |
      cd contracts
      rustup default stable
      rustup update
      rustup target add wasm32-unknown-unknown
      cargo build --target wasm32-unknown-unknown --release
    command: |
      cd contracts
      cargo test
  - init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm start

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8000
    onOpen: open-preview

github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true

# Remove the vscode section as it's not a valid property in gitpod.yml
# vscode:
#   extensions:
#     - dbaeumer.vscode-eslint
#     - esbenp.prettier-vscode
#     - rust-lang.rust-analyzer

# Remove the env section as it's not a valid property in gitpod.yml
# env:
#   NODE_ENV: development