# Specify the Docker image to use for the Gitpod environment
image:
  file: .gitpod.Dockerfile

# Define the tasks to run in the Gitpod environment
tasks:
  # Initial task to install npm packages and start the main application
  - init: npm install
    command: npm start

  # Task to initialize and start the backend
  - init: |
      cd backend
      npm install
      npm run dev
    command: |
      cd backend
      npm start

  # Task to initialize and build Soroban smart contracts
  - init: |
      cd contracts
      rustup default stable
      rustup update
      rustup target add wasm32-unknown-unknown
      cargo build --target wasm32-unknown-unknown --release
    command: |
      cd contracts
      cargo test

  # Task to initialize and start the React frontend
  - init: |
      cd frontend
      npm install
    command: |
      cd frontend
      npm start

# Define the ports to expose and their behavior when opened
ports:
  - port: 3000
    onOpen: open-preview
  - port: 8000
    onOpen: open-preview

# Specify VS Code extensions to install in the Gitpod environment
vscode:
  extensions:
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - rust-lang.rust-analyzer

# Configure prebuilds for GitHub branches and pull requests
github:
  prebuilds:
    master: true
    branches: true
    pullRequests: true

# Set environment variables for the Gitpod environment
env:
  NODE_ENV: development
